version: '3.8'
services:
  postgres-topic:
    container_name: postgres-topic
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=topic_service
    ports:
      - "5431:5431"
    expose:
      - "5431"
    command: -p 5431
    restart: always

  postgres-choose-side:
    container_name: postgres-choose-side
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=choose_side_service
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command: -p 5432
    restart: always

  postgres-opinion:
    container_name: postgres-opinion
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opinion_service
    ports:
      - "5433:5433"
    expose:
      - "5433"
    command: -p 5433
    restart: always

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
     - "9411:9411"
    expose:
      - "9411"
    command: -p 9411


  discovery-server:
    image: 10k920/discovery-server:latest
    container_name: discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    expose:
      - "8761"
    command: -p 8761
    depends_on:
      - zipkin

  api-gateway:
    image: 10k920/api-gateway:latest
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - zipkin
      - discovery-server

  topic-service:
    image: 10k920/topic-service:latest
    container_name: topic-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - discovery-server
      - api-gateway
      - postgres-topic

  choose-side-service:
    image: 10k920/choose-side-service:latest
    container_name: choose-side-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - discovery-server
      - api-gateway
      - postgres-choose-side

  opinion-service:
    image: 10k920/opinion-service:latest
    container_name: opinion-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - discovery-server
      - api-gateway
      - postgres-opinion


